### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by onetrev** [carlo/behave-theme#3]
Unfortunately with Atom removing support for the shadow DOM, the theme now results in deprecation warnings. 

"Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary.  This means you should stop using :host and ::shadow pseudo-selectors, and prepend all your syntax selectors with syntax--."

Hopefully / likely a find and replace should resolve these.

Cheers!

**Comment by czottmann** [comment]
It's on my radar as well as my todo list, I just haven't found the time to fix it.

@onetrev, I just saw your PR, thanks for that — I'll look at it in the next two days!

**Comment by czottmann** [comment]
Fixed, 1.7.0 was released!
